### PR TITLE
Create Monica-Wish-List

### LINKED ISSUE #29: Monica Christmas Wish
- [ ] Purse
- [ ] Watch 
- [ ] Boots 
- [ ] Personal Assistant 
- [ ] Trip

### PR DESCRIPTION
**Pull request by monicanpm**
Resolves #29

### CODE REVIEW

**Comment by watridge** [comment]
love the list

**Comment by AMZod** [comment]
:sheep:

**Comment by rod11** [comment]
:sheep:

**Comment by EmilyUna65** [comment]
Typo!

**Pull request merged**
